// <auto-generated />
namespace tweb.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CreateTwebUserTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("tweb.DAL.Migrations.202505170316306_CreateTwebUserTable", typeof(CreateTwebUserTable).Assembly);

        string IMigrationMetadata.Id
        {
            get { return "202505170316306_CreateTwebUserTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
